version: 0.2

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - zip devopsassi-dep-pkg.zip lambdacode.py
  build:
    on-failure: ABORT
    commands:
      - aws lambda update-function-code --function-name DevOpsAssiManLamb --zip-file fileb://devopsassi-dep-pkg.zip
  post_build:
    on-failure: ABORT
    commands:
      - aws cloudformation package --template-file cloudformationscript.yaml --s3-bucket DevOpsAssiBucket --output-template-file packagedcfscript.yaml
      